// js/configurator/console-data.js — Données des consoles (sans prix, sans mods)

export const CONSOLE_CONFIGS = {
    gameboy_dmg: {
        modelPath: "models/gameboy_dmg.glb",
        cameraSettings: {
            position: { x: 0, y: 0.001, z: 0.14 },
            zoomMin: 0.12,
            zoomMax: 0.19,
            zoomSpeed: 0.01,
            mobileYOffset: 0,
            mobileZOffset: 0.01,
            mobileZoomMin: 0.12,
            mobileZoomMax: 0.19,
        },
        lightsPreset: "standard",
        behavior: "gameboy",
        logoMaterialName: 'material.006',
        backSyncCheckOpacity: true,
        colorSlides: [
            { title: "Coque", pickerId: "face-color-picker", materialName: "faceMaterial" },
            { title: "Coque arrière", pickerId: "back-color-picker", materialName: "backMaterial" },
            { title: "Écran", pickerId: "screen-color-picker", materialName: "screenMaterial" },
            { title: "Power Led", pickerId: "led-color-picker", materialName: "ledMaterial" },
            { title: "Boutons", pickerId: "buttons-color-picker", materialName: "buttonsMaterial" },
            { title: "Start / Select", pickerId: "button-start-color-picker", materialName: "buttonStartMaterial" },
        ],
        colorPalettes: {
            faceMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                gray: { color: "#c9c6c7", opacity: 1, name: "Gray" },
                red: { color: "#ae1d1c", opacity: 1, name: "Red" },
                goldensun: { color: "#e49d23", opacity: 1, name: "Golden Sun" },
                orange: { color: "#ef6f10", opacity: 1, name: "Orange" },
                blue: { color: "#282a8b", opacity: 1, name: "Blue" },
                green: { color: "#61ad46", opacity: 1, name: "Green" },
                clear: { color: "#ffffff", opacity: 0.85, name: "Clear" },
                clearblack: { color: "#2d3132", opacity: 0.85, name: "Clear Black" },
            },
            backMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                gray: { color: "#c9c6c7", opacity: 1, name: "Gray" },
                red: { color: "#ae1d1c", opacity: 1, name: "Red" },
                goldensun: { color: "#e49d23", opacity: 1, name: "Golden Sun" },
                orange: { color: "#ef6f10", opacity: 1, name: "Orange" },
                blue: { color: "#282a8b", opacity: 1, name: "Blue" },
                green: { color: "#61ad46", opacity: 1, name: "Green" },
                clear: { color: "#ffffff", opacity: 0.85, name: "Clear" },
                clearblack: { color: "#2d3132", opacity: 0.85, name: "Clear Black" },
            },
            screenMaterial: {
                whitescreen: { color: "#ffffff", opacity: 1, name: "White" },
                blackscreen: { color: "#050505", opacity: 1, name: "Black" },
                goldscreen: { color: "#918157", opacity: 1, name: "Gold" },
                bluescreen: { color: "#2d5aad", opacity: 1, name: "Blue" },
                redscreen: { color: "#d90900", opacity: 1, name: "Red" },
            },
            ledMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                red: { name: "Red", color: "#ff0000", opacity: 1 },
                green: { name: "Green", color: "#00ff00", opacity: 1 },
                yellow: { name: "Yellow", color: "#fff200", opacity: 1 },
                orange: { name: "Orange", color: "#ff8800", opacity: 1 },
                pink: { name: "Pink", color: "#ff00f7", opacity: 1 },
                blue: { name: "Blue", color: "#00ccff", opacity: 1 },
            },
            buttonsMaterial: {
                whitebutton: { color: "#ffffff", opacity: 1, name: "White" },
                blackbutton: { color: "#050505", opacity: 1, name: "Black" },
                bluebutton: { color: "#1d2ea6", opacity: 1, name: "Blue" },
                cyanbutton: { color: "#3e97b5", opacity: 1, name: "Cyan" },
                yellowbutton: { color: "#f5bd45", opacity: 1, name: "Yellow" },
                orangebutton: { color: "#ff822b", opacity: 1, name: "Orange" },
                redbutton: { color: "#bb2429", opacity: 1, name: "Red" },
                purpleredbutton: { color: "#7b1634", opacity: 1, name: "Purple Red" },
                greenbutton: { color: "#6eb824", opacity: 1, name: "Green" },
                clearbutton: { color: "#ffffff", opacity: 0.6, name: "Clear" },
                clearblackbutton: { color: "#303435", opacity: 0.6, name: "Clear Black" },
                clearbluebutton: { color: "#20a3f8", opacity: 0.6, name: "Clear Blue" },
                cleargreenbutton: { color: "#50bf45", opacity: 0.6, name: "Clear Green" },
                clearorangebutton: { color: "#fe8c0e", opacity: 0.6, name: "Clear Orange" },
            },
            buttonStartMaterial: {
                whitetampon: { color: "#ffffff", opacity: 1, name: "White" },
                blacktampon: { color: "#050505", opacity: 1, name: "Black" },
                graytampon: { color: "#938b87", opacity: 1, name: "Gray" },
                bluetampon: { color: "#2450c5", opacity: 1, name: "Blue" },
                redtampon: { color: "#ea3231", opacity: 1, name: "Red" },
                yellowtampon: { color: "#ebca28", opacity: 1, name: "Yellow" },
                greentampon: { color: "#a6d445", opacity: 1, name: "Green" },
                purpletampon: { color: "#623b84", opacity: 1, name: "Purple" },
            },
        },
    },

    gameboy_pocket: {
        modelPath: "models/gameboy_pocket.glb",
        cameraSettings: {
            position: { x: 0.07, y: 0.009, z: 2.6 },
            zoomMin: 2.0,
            zoomMax: 3.5,
            zoomSpeed: 0.05,
            mobileYOffset: 0,
            mobileZOffset: 0.3,
            mobileZoomMin: 2.0,
            mobileZoomMax: 3.5,
            cameraNear: 0.1,
        },
        lightsPreset: "standard",
        behavior: "gameboy",
        logoMaterialName: 'material.005',
        backSyncCheckOpacity: true,
        colorSlides: [
            { title: "Coque", pickerId: "face-color-picker", materialName: "faceMaterial" },
            { title: "Coque arrière", pickerId: "back-color-picker", materialName: "backMaterial" },
            { title: "Écran", pickerId: "screen-color-picker", materialName: "screenMaterial" },
            { title: "Power Led", pickerId: "led-color-picker", materialName: "ledMaterial" },
            { title: "Boutons", pickerId: "buttons-color-picker", materialName: "buttonsMaterial" },
            { title: "Start / Select", pickerId: "button-start-color-picker", materialName: "buttonStartMaterial" },
        ],
        colorPalettes: {
            faceMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                gray: { name: "Gray", color: "#adaba9", opacity: 1 },
                yellow: { name: "Yellow", color: "#fec409", opacity: 1 },
                rolandpurple: { name: "Roland Purple", color: "#b9aff0", opacity: 1 },
                pink: { name: "Pink", color: "#f2c5d2", opacity: 1 },
                "clear-light-cyan": { name: "Clear Light Cyan", color: "#98f0eb", opacity: 0.93 },
                "clear-red": { name: "Clear Red", color: "#c40f15", opacity: 0.93 },
                clear: { name: "Clear", color: "#ffffff", opacity: 0.85 },
                "clear-black": { name: "Clear Black", color: "#2d3132", opacity: 0.85 },
                "clear-yellow": { name: "Clear Yellow", color: "#fec409", opacity: 0.9 },
                "clear-light-purple": { name: "Clear Light Purple", color: "#7b7290", opacity: 0.85 },
                "clear-orange": { name: "Clear Orange", color: "#fe4e06", opacity: 0.9 },
                "clear-green": { name: "Clear Green", color: "#33bb2e", opacity: 0.9 },
                "clear-blue": { name: "Clear Blue", color: "#0175a3", opacity: 0.9 },
            },
            backMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                gray: { name: "Gray", color: "#adaba9", opacity: 1 },
                yellow: { name: "Yellow", color: "#fec409", opacity: 1 },
                rolandpurple: { name: "Roland Purple", color: "#b9aff0", opacity: 1 },
                pink: { name: "Pink", color: "#f2c5d2", opacity: 1 },
                "clear-light-cyan": { name: "Clear Light Cyan", color: "#98f0eb", opacity: 0.93 },
                "clear-red": { name: "Clear Red", color: "#c40f15", opacity: 0.93 },
                clear: { name: "Clear", color: "#ffffff", opacity: 0.85 },
                "clear-black": { name: "Clear Black", color: "#2d3132", opacity: 0.85 },
                "clear-yellow": { name: "Clear Yellow", color: "#fec409", opacity: 0.9 },
                "clear-light-purple": { name: "Clear Light Purple", color: "#7b7290", opacity: 0.85 },
                "clear-orange": { name: "Clear Orange", color: "#fe4e06", opacity: 0.9 },
                "clear-green": { name: "Clear Green", color: "#33bb2e", opacity: 0.9 },
                "clear-blue": { name: "Clear Blue", color: "#0175a3", opacity: 0.9 },
            },
            screenMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                darkgray: { name: "Dark Gray", color: "#726a72", opacity: 1 },
            },
            ledMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                red: { name: "Red", color: "#ff0000", opacity: 1 },
                green: { name: "Green", color: "#00ff00", opacity: 1 },
                yellow: { name: "Yellow", color: "#fff200", opacity: 1 },
                orange: { name: "Orange", color: "#ff8800", opacity: 1 },
                pink: { name: "Pink", color: "#ff00f7", opacity: 1 },
                blue: { name: "Blue", color: "#00ccff", opacity: 1 },
            },
            buttonsMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                blue: { name: "Blue", color: "#3065c0", opacity: 1 },
                lightgreen: { name: "Light Green", color: "#15ddd1", opacity: 1 },
                yellow: { name: "Yellow", color: "#fec409", opacity: 1 },
                red: { name: "Red", color: "#a41408", opacity: 1 },
                pink: { name: "Pink", color: "#ff83ab", opacity: 1 },
                green: { name: "Green", color: "#95b853", opacity: 1 },
                clear: { name: "Clear", color: "#ffffff", opacity: 0.6 },
                "clear-black": { name: "Clear Black", color: "#303435", opacity: 0.6 },
                "clear-light-blue": { name: "Clear Light Blue", color: "#35bdf3", opacity: 0.6 },
                "clear-green": { name: "Clear Green", color: "#6fda42", opacity: 0.6 },
                "clear-orange": { name: "Clear Orange", color: "#ef6f3d", opacity: 0.6 },
            },
            buttonStartMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                lightblue: { name: "Light Blue", color: "#35bdf3", opacity: 1 },
                blue: { name: "Blue", color: "#3d60d5", opacity: 1 },
                red: { name: "Red", color: "#e6362e", opacity: 1 },
                yellow: { name: "Yellow", color: "#eed926", opacity: 1 },
                green: { name: "Green", color: "#acd653", opacity: 1 },
                pink: { name: "Pink", color: "#dc83aa", opacity: 1 },
            },
        },
    },

    gameboy_color: {
        modelPath: "models/gameboy_color.glb",
        cameraSettings: {
            position: { x: 0, y: 0.009, z: 0.19 },
            zoomMin: 0.16,
            zoomMax: 0.26,
            zoomSpeed: 0.01,
            mobileYOffset: 0,
            mobileZOffset: 0,
            mobileZoomMin: 0.16,
            mobileZoomMax: 0.26,
        },
        lightsPreset: "standard",
        behavior: "gameboy",
        logoMaterialName: 'material.003',
        backSyncCheckOpacity: true,
        colorSlides: [
            { title: "Coque", pickerId: "face-color-picker", materialName: "faceMaterial" },
            { title: "Coque arrière", pickerId: "back-color-picker", materialName: "backMaterial" },
            { title: "Écran", pickerId: "screen-color-picker", materialName: "screenMaterial" },
            { title: "Power Led", pickerId: "led-color-picker", materialName: "ledMaterial" },
            { title: "Boutons", pickerId: "buttons-color-picker", materialName: "buttonsMaterial" },
            { title: "Start / Select", pickerId: "button-start-color-picker", materialName: "buttonStartMaterial" },
        ],
        colorPalettes: {
            faceMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                gray: { name: "Gray", color: "#adaba9", opacity: 1 },
                cyanblue: { name: "Cyan Blue", color: "#98f0eb", opacity: 1 },
                yellow: { name: "Yellow", color: "#fec409", opacity: 1 },
                orange: { name: "Orange", color: "#fe823f", opacity: 1 },
                rolandpurple: { name: "Roland Purple", color: "#b9aff0", opacity: 1 },
                pink: { name: "Pink", color: "#f2c5d2", opacity: 1 },
                "clear-light-cyan": { name: "Clear Light Cyan", color: "#98f0eb", opacity: 0.93 },
                "clear-red": { name: "Clear Red", color: "#c40f15", opacity: 0.93 },
                clear: { name: "Clear", color: "#ffffff", opacity: 0.85 },
                "clear-black": { name: "Clear Black", color: "#2d3132", opacity: 0.85 },
                "clear-yellow": { name: "Clear Yellow", color: "#fec409", opacity: 0.9 },
                "clear-light-purple": { name: "Clear Light Purple", color: "#7b7290", opacity: 0.85 },
                "clear-deep-blue": { name: "Clear Deep Blue", color: "#042faf", opacity: 0.9 },
                "clear-orange": { name: "Clear Orange", color: "#fe4e06", opacity: 0.9 },
                "clear-green": { name: "Clear Green", color: "#33bb2e", opacity: 0.9 },
                "clear-mist-blue": { name: "Clear Mist Blue", color: "#5fa0ea", opacity: 0.97 },
            },
            backMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                gray: { name: "Gray", color: "#adaba9", opacity: 1 },
                cyanblue: { name: "Cyan Blue", color: "#98f0eb", opacity: 1 },
                yellow: { name: "Yellow", color: "#fec409", opacity: 1 },
                orange: { name: "Orange", color: "#fe823f", opacity: 1 },
                rolandpurple: { name: "Roland Purple", color: "#b9aff0", opacity: 1 },
                pink: { name: "Pink", color: "#f2c5d2", opacity: 1 },
                "clear-light-cyan": { name: "Clear Light Cyan", color: "#98f0eb", opacity: 0.93 },
                "clear-red": { name: "Clear Red", color: "#c40f15", opacity: 0.93 },
                clear: { name: "Clear", color: "#ffffff", opacity: 0.85 },
                "clear-black": { name: "Clear Black", color: "#2d3132", opacity: 0.85 },
                "clear-yellow": { name: "Clear Yellow", color: "#fec409", opacity: 0.9 },
                "clear-light-purple": { name: "Clear Light Purple", color: "#7b7290", opacity: 0.85 },
                "clear-deep-blue": { name: "Clear Deep Blue", color: "#042faf", opacity: 0.9 },
                "clear-orange": { name: "Clear Orange", color: "#fe4e06", opacity: 0.9 },
                "clear-green": { name: "Clear Green", color: "#33bb2e", opacity: 0.9 },
                "clear-mist-blue": { name: "Clear Mist Blue", color: "#5fa0ea", opacity: 0.97 },
            },
            screenMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                darkgray: { name: "Dark Gray", color: "#726a72", opacity: 1 },
                lightgray: { name: "Light Gray", color: "#cfd0c9", opacity: 1 },
                lightblue: { name: "Light Blue", color: "#a8d3d0", opacity: 1 },
                darkblue: { name: "Dark Blue", color: "#1e369e", opacity: 1 },
                yellow: { name: "Yellow", color: "#fec409", opacity: 1 },
                green: { name: "Green", color: "#2c6932", opacity: 1 },
                red: { name: "Red", color: "#831914", opacity: 1 },
                orange: { name: "Orange", color: "#e4520d", opacity: 1 },
                purple: { name: "Purple", color: "#b4a0d5", opacity: 1 },
                pink: { name: "Pink", color: "#d1a0a8", opacity: 1 },
            },
            ledMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                red: { name: "Red", color: "#ff0000", opacity: 1 },
                green: { name: "Green", color: "#00ff00", opacity: 1 },
                yellow: { name: "Yellow", color: "#fff200", opacity: 1 },
                orange: { name: "Orange", color: "#ff8800", opacity: 1 },
                pink: { name: "Pink", color: "#ff00f7", opacity: 1 },
                blue: { name: "Blue", color: "#00ccff", opacity: 1 },
            },
            buttonsMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                blue: { name: "Blue", color: "#3065c0", opacity: 1 },
                lightgreen: { name: "Light Green", color: "#bce1c5", opacity: 1 },
                yellow: { name: "Yellow", color: "#fec409", opacity: 1 },
                red: { name: "Red", color: "#a41408", opacity: 1 },
                purplered: { name: "Purple Red", color: "#73345c", opacity: 1 },
                purple: { name: "Purple", color: "#d3b1e9", opacity: 1 },
                pink: { name: "Pink", color: "#f5bcbd", opacity: 1 },
                green: { name: "Green", color: "#156327", opacity: 1 },
                clear: { name: "Clear", color: "#ffffff", opacity: 0.6 },
                "clear-black": { name: "Clear Black", color: "#303435", opacity: 0.6 },
                "clear-blue": { name: "Clear Blue", color: "#47939b", opacity: 0.6 },
                "ice-blue": { name: "Ice Blue", color: "#83ad9a", opacity: 0.6 },
                "clear-green": { name: "Clear Green", color: "#4e9e53", opacity: 0.6 },
                "clear-yellow": { name: "Clear Yellow", color: "#f6fd39", opacity: 0.6 },
                "clear-orange": { name: "Clear Orange", color: "#ef6f3d", opacity: 0.6 },
            },
            buttonStartMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                gray: { name: "Gray", color: "#a9a7a5", opacity: 1 },
                lightblue: { name: "Light Blue", color: "#9bd5c3", opacity: 1 },
                blue: { name: "Blue", color: "#3d60d5", opacity: 1 },
                red: { name: "Red", color: "#e6362e", opacity: 1 },
                yellow: { name: "Yellow", color: "#eed926", opacity: 1 },
                green: { name: "Green", color: "#acd653", opacity: 1 },
                purple: { name: "Purple", color: "#6e4796", opacity: 1 },
                pink: { name: "Pink", color: "#e6bcc1", opacity: 1 },
            },
        },
    },

    gameboy_advance: {
        modelPath: "models/gameboy_advance.glb",
        cameraSettings: {
            position: { x: 0, y: 0.012, z: 0.33 },
            zoomMin: 0.26,
            zoomMax: 0.52,
            zoomSpeed: 0.015,
            mobileYOffset: 0,
            mobileZOffset: 0.03,
            mobileZoomMin: 0.28,
            mobileZoomMax: 0.55,
        },
        lightsPreset: "standard",
        behavior: "gameboy",
        logoMaterialName: 'material',
        backSyncCheckOpacity: false,
        colorSlides: [
            { title: "Coque", pickerId: "face-color-picker", materialName: "faceMaterial" },
            { title: "Coque arrière", pickerId: "back-color-picker", materialName: "backMaterial" },
            { title: "Écran", pickerId: "screen-color-picker", materialName: "screenMaterial" },
            { title: "Boutons", pickerId: "buttons-color-picker", materialName: "buttonsMaterial" },
            { title: "Start / Select", pickerId: "button-start-color-picker", materialName: "buttonStartMaterial" },
        ],
        colorPalettes: {
            faceMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                gray: { color: "#c8bebf", opacity: 1, name: "Gray" },
                cyanblue: { color: "#c4e0e7", opacity: 1, name: "Cyan Blue" },
                yellow: { color: "#ecc227", opacity: 1, name: "Yellow" },
                purple: { color: "#a78fe0", opacity: 1, name: "Purple" },
                pink: { color: "#f2d4d7", opacity: 1, name: "Pink" },
                clear: { color: "#ffffff", opacity: 0.85, name: "Clear" },
                clearblack: { color: "#2d3132", opacity: 0.85, name: "Clear Black" },
                clearmistycyan: { color: "#a5d3d1", opacity: 0.93, name: "Clear Misty Cyan" },
                clearorange: { color: "#fe4e06", opacity: 0.9, name: "Clear Orange" },
                clearred: { color: "#d0191d", opacity: 0.93, name: "Clear Red" },
                cleardarkblue: { color: "#042faf", opacity: 0.9, name: "Clear Dark Blue" },
                clearlightblue: { color: "#5fa0ea", opacity: 0.97, name: "Clear Light Blue" },
                clearpurple: { color: "#603c91", opacity: 0.85, name: "Clear Purple" },
                cleargreen: { color: "#33bb2e", opacity: 0.9, name: "Clear Green" },
            },
            backMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                gray: { color: "#c8bebf", opacity: 1, name: "Gray" },
                cyanblue: { color: "#c4e0e7", opacity: 1, name: "Cyan Blue" },
                yellow: { color: "#ecc227", opacity: 1, name: "Yellow" },
                purple: { color: "#a78fe0", opacity: 1, name: "Purple" },
                pink: { color: "#f2d4d7", opacity: 1, name: "Pink" },
                clear: { color: "#ffffff", opacity: 0.85, name: "Clear" },
                clearblack: { color: "#2d3132", opacity: 0.85, name: "Clear Black" },
                clearmistycyan: { color: "#a5d3d1", opacity: 0.93, name: "Clear Misty Cyan" },
                clearorange: { color: "#fe4e06", opacity: 0.9, name: "Clear Orange" },
                clearred: { color: "#d0191d", opacity: 0.93, name: "Clear Red" },
                cleardarkblue: { color: "#042faf", opacity: 0.9, name: "Clear Dark Blue" },
                clearlightblue: { color: "#5fa0ea", opacity: 0.97, name: "Clear Light Blue" },
                clearpurple: { color: "#603c91", opacity: 0.85, name: "Clear Purple" },
                cleargreen: { color: "#33bb2e", opacity: 0.9, name: "Clear Green" },
            },
            screenMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
                red: { name: "Red", color: "#713633", opacity: 1 },
            },
            buttonsMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                blue: { color: "#5f6ab7", opacity: 1, name: "Blue" },
                green: { color: "#95b617", opacity: 1, name: "Green" },
                yellow: { color: "#f5dd22", opacity: 1, name: "Yellow" },
                red: { color: "#dc1716", opacity: 1, name: "Red" },
                clear: { color: "#ffffff", opacity: 0.6, name: "Clear" },
                clearblack: { color: "#303435", opacity: 0.6, name: "Clear Black" },
                clearskyblue: { color: "#3f8fbf", opacity: 0.6, name: "Clear Sky Blue" },
                clearblue: { color: "#463f8d", opacity: 0.6, name: "Clear Blue" },
                cleargreen: { color: "#5da951", opacity: 0.6, name: "Clear Green" },
                clearorange: { color: "#e55904", opacity: 0.6, name: "Clear Orange" },
            },
            buttonStartMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                gray: { color: "#cbc9c5", opacity: 1, name: "Gray" },
                skyblue: { color: "#3596e3", opacity: 1, name: "Sky Blue" },
                blue: { color: "#132ac4", opacity: 1, name: "Blue" },
                red: { color: "#cc1f13", opacity: 1, name: "Red" },
                yellow: { color: "#fce400", opacity: 1, name: "Yellow" },
                green: { color: "#018d74", opacity: 1, name: "Green" },
                peachred: { color: "#971f52", opacity: 1, name: "Peach Red" },
                pink: { color: "#dd419c", opacity: 1, name: "Pink" },
            },
        },
    },

    gameboy_advance_sp: {
        modelPath: "models/gameboy_advance_sp.glb",
        cameraSettings: {
            position: { x: 0, y: 0.3, z: 4.2 },
            zoomMin: 3.2,
            zoomMax: 5.5,
            zoomSpeed: 0.05,
            mobileYOffset: 0,
            mobileZOffset: 0.6,
            mobileZoomMin: 3.5,
            mobileZoomMax: 6.0,
        },
        lightsPreset: "standard",
        behavior: "gameboy",
        logoMaterialName: 'material.004',
        backSyncCheckOpacity: false,
        colorSlides: [
            { title: "Coque", pickerId: "face-color-picker", materialName: "faceMaterial" },
            { title: "Coque arrière", pickerId: "back-color-picker", materialName: "backMaterial" },
            { title: "Écran", pickerId: "screen-color-picker", materialName: "screenMaterial" },
            { title: "Boutons", pickerId: "buttons-color-picker", materialName: "buttonsMaterial" },
            { title: "Membranes", pickerId: "button-start-color-picker", materialName: "buttonStartMaterial" },
        ],
        colorPalettes: {
            faceMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                lightgreen: { color: "#81dbd1", opacity: 1, name: "Light Green" },
                yellow: { color: "#f6d304", opacity: 1, name: "Yellow" },
                purple: { color: "#957dbc", opacity: 1, name: "Purple" },
                pink: { color: "#f1cbd3", opacity: 1, name: "Pink" },
                clearred: { color: "#d12725", opacity: 0.93, name: "Clear Red" },
                clear: { color: "#ffffff", opacity: 0.85, name: "Clear" },
                clearblack: { color: "#2d3132", opacity: 0.85, name: "Clear Black" },
                clearpurple: { color: "#c5a9c3", opacity: 0.85, name: "Clear Purple" },
                cleardarkpurple: { color: "#7e449e", opacity: 0.85, name: "Clear Dark Purple" },
                clearblue: { color: "#356bd1", opacity: 0.85, name: "Clear Blue" },
                clearorange: { color: "#fd8f40", opacity: 0.9, name: "Clear Orange" },
                cleargreen: { color: "#87d072", opacity: 0.9, name: "Clear Green" },
                fluorescentblue: { color: "#a4bdd9", opacity: 0.95, name: "Fluorescent Blue" },
            },
            backMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                lightgreen: { color: "#81dbd1", opacity: 1, name: "Light Green" },
                yellow: { color: "#f6d304", opacity: 1, name: "Yellow" },
                purple: { color: "#957dbc", opacity: 1, name: "Purple" },
                pink: { color: "#f1cbd3", opacity: 1, name: "Pink" },
                clearred: { color: "#d12725", opacity: 0.93, name: "Clear Red" },
                clear: { color: "#ffffff", opacity: 0.85, name: "Clear" },
                clearblack: { color: "#2d3132", opacity: 0.85, name: "Clear Black" },
                clearpurple: { color: "#c5a9c3", opacity: 0.85, name: "Clear Purple" },
                cleardarkpurple: { color: "#7e449e", opacity: 0.85, name: "Clear Dark Purple" },
                clearblue: { color: "#356bd1", opacity: 0.85, name: "Clear Blue" },
                clearorange: { color: "#fd8f40", opacity: 0.9, name: "Clear Orange" },
                cleargreen: { color: "#87d072", opacity: 0.9, name: "Clear Green" },
                fluorescentblue: { color: "#a4bdd9", opacity: 0.95, name: "Fluorescent Blue" },
            },
            screenMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                black: { name: "Black", color: "#050505", opacity: 1 },
            },
            buttonsMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#050505", opacity: 1, name: "Black" },
                blue: { color: "#3354bb", opacity: 1, name: "Blue" },
                lightblue: { color: "#74c9ff", opacity: 1, name: "Light Blue" },
                skyblue: { color: "#72e7ff", opacity: 1, name: "Sky Blue" },
                green: { color: "#29d8b2", opacity: 1, name: "Green" },
                darkgreen: { color: "#419d97", opacity: 1, name: "Dark Green" },
                yellow: { color: "#f2c85d", opacity: 1, name: "Yellow" },
                red: { color: "#952d34", opacity: 1, name: "Red" },
                purple: { color: "#3d2881", opacity: 1, name: "Purple" },
                clear: { color: "#ffffff", opacity: 0.6, name: "Clear" },
                clearblack: { color: "#303435", opacity: 0.6, name: "Clear Black" },
                clearblue: { color: "#1e6396", opacity: 0.6, name: "Clear Blue" },
                clearred: { color: "#911f28", opacity: 0.6, name: "Clear Red" },
                cleargreen: { color: "#56872c", opacity: 0.6, name: "Clear Green" },
                clearyellow: { color: "#c5aa40", opacity: 0.6, name: "Clear Yellow" },
                clearpurple: { color: "#998ab0", opacity: 0.6, name: "Clear Purple" },
                clearpink: { color: "#d25073", opacity: 0.6, name: "Clear Pink" },
            },
            buttonStartMaterial: {
                white: { color: "#ffffff", opacity: 1, name: "White" },
                black: { color: "#474747", opacity: 1, name: "Black" },
                gray: { color: "#cbc9c5", opacity: 1, name: "Gray" },
                skyblue: { color: "#3596e3", opacity: 1, name: "Sky Blue" },
                blue: { color: "#132ac4", opacity: 1, name: "Blue" },
                red: { color: "#cc1f13", opacity: 1, name: "Red" },
                yellow: { color: "#fce400", opacity: 1, name: "Yellow" },
                green: { color: "#018d74", opacity: 1, name: "Green" },
                peachred: { color: "#971f52", opacity: 1, name: "Peach Red" },
                pink: { color: "#dd419c", opacity: 1, name: "Pink" },
                turquoise: { color: "#4cb7b8", opacity: 1, name: "Turquoise" },
            },
        },
    },

    gamecube: {
        modelPath: "models/gamecube.glb",
        cameraSettings: {
            position: { x: 0, y: 0.15, z: 2.5 },
            zoomMin: 1.9,
            zoomMax: 3.4,
            zoomSpeed: 0.08,
            mobileYOffset: 0,
            mobileZOffset: 0.4,
            mobileZoomMin: 2.0,
            mobileZoomMax: 3.4,
        },
        lightsPreset: "bright",
        behavior: "gamecube",
        backSyncCheckOpacity: false,
        colorSlides: [
            { title: "Boîtier", pickerId: "face-color-picker", materialName: "faceMaterial" },
            { title: "Power LED", pickerId: "led-color-picker", materialName: "ledMaterial" },
            { title: "LED Port Manette", pickerId: "led-controller-color-picker", materialName: "LedControllerMaterial" },
        ],
        colorPalettes: {
            faceMaterial: {
                red: { name: "Red", color: "#d7452b", opacity: 1 },
                orange: { name: "Orange", color: "#fea156", opacity: 1 },
                clear: { name: "Clear", color: "#ffffff", opacity: 0.6 },
                "clear-black": { name: "Clear Black", color: "#1e1d17", opacity: 0.6 },
                "clear-purple": { name: "Clear Purple", color: "#4e0073", opacity: 0.6 },
                "clear-green": { name: "Clear Green", color: "#027e49", opacity: 0.6 },
                "clear-trngreen": { name: "Clear TRN Green", color: "#c9f60d", opacity: 0.6 },
                "clear-orange": { name: "Clear Orange", color: "#fc6102", opacity: 0.6 },
                "clear-blue": { name: "Clear Blue", color: "#0e2085", opacity: 0.6 },
                "clear-skyblue": { name: "Clear Sky Blue", color: "#6fcae7", opacity: 0.6 },
            },
            ledMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                red: { name: "Red", color: "#ff0000", opacity: 1 },
                green: { name: "Green", color: "#00ff00", opacity: 1 },
                yellow: { name: "Yellow", color: "#fff200", opacity: 1 },
                orange: { name: "Orange", color: "#ff8800", opacity: 1 },
                pink: { name: "Pink", color: "#ff00f7", opacity: 1 },
                blue: { name: "Blue", color: "#00ccff", opacity: 1 },
            },
            LedControllerMaterial: {
                white: { name: "White", color: "#ffffff", opacity: 1 },
                red: { name: "Red", color: "#ff0000", opacity: 1 },
                green: { name: "Green", color: "#00ff00", opacity: 1 },
                yellow: { name: "Yellow", color: "#fff200", opacity: 1 },
                orange: { name: "Orange", color: "#ff8800", opacity: 1 },
                pink: { name: "Pink", color: "#ff00f7", opacity: 1 },
                blue: { name: "Blue", color: "#00ccff", opacity: 1 },
            },
        },
        plasticSyncRules: {
            syncClear: ["Clear Purple", "Clear Black"],
            forcePlastic2Black: ["Purple", "Orange"],
            forceAllBlack: ["Red"],
            forcePlasticToGray: ["Orange"],
        },
    },
};
