blank_issues_enabled: true
contact_links:
  - name: 💬 Discord OpenPixel Lab
    url: https://discord.gg/jgE5CAmXw2
    about: Pour discuter, poser une question, ou proposer un gros ajout (nouvelle console, gros tuto).
